import { Product, SellRequest, SaleData } from './types';

export const PRODUCTS: Product[] = [
  // ... existing products (I'll keep them as is)
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    category: 'iPhone',
    price: 4899,
    originalPrice: 5499,
    image: 'https://picsum.photos/seed/iphone15pm/600/600',
    description: 'The ultimate iPhone with Titanium design, A17 Pro chip, and advanced camera system.',
    condition: 'Excellent',
    stock: 10,
    specs: {
      storage: '256GB',
      color: 'Natural Titanium',
      screen: '6.7-inch Super Retina XDR',
    },
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    category: 'iPhone',
    price: 3299,
    originalPrice: 3999,
    image: 'https://picsum.photos/seed/iphone14p/600/600',
    description: 'Pro. Beyond. Featuring Dynamic Island and Always-On display.',
    condition: 'Excellent',
    stock: 5,
    specs: {
      storage: '128GB',
      color: 'Deep Purple',
      screen: '6.1-inch Super Retina XDR',
    },
  },
  {
    id: 'ipad-pro-m2',
    name: 'iPad Pro 11-inch (M2)',
    category: 'iPad',
    price: 3499,
    originalPrice: 3899,
    image: 'https://picsum.photos/seed/ipadpro/600/600',
    description: 'Astonishing performance. Incredibly advanced displays. Superfast wireless connectivity.',
    condition: 'Excellent',
    stock: 8,
    specs: {
      storage: '256GB',
      color: 'Space Gray',
      connectivity: 'Wi-Fi',
    },
  },
  {
    id: 'macbook-air-m2',
    name: 'MacBook Air 13-inch (M2)',
    category: 'MacBook',
    price: 4299,
    originalPrice: 4799,
    image: 'https://picsum.photos/seed/macbookair/600/600',
    description: 'Strikingly thin design. Supercharged by M2. Up to 18 hours of battery life.',
    condition: 'Excellent',
    stock: 3,
    specs: {
      processor: 'Apple M2 chip',
      memory: '8GB',
      storage: '256GB SSD',
    },
  },
  {
    id: 'apple-watch-s9',
    name: 'Apple Watch Series 9',
    category: 'Watch',
    price: 1599,
    originalPrice: 1899,
    image: 'https://picsum.photos/seed/watch9/600/600',
    description: 'Smarter. Brighter. Mightier. The most powerful chip in Apple Watch ever.',
    condition: 'Excellent',
    stock: 12,
    specs: {
      size: '45mm',
      material: 'Aluminum',
      band: 'Sport Band',
    },
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro (2nd Gen)',
    category: 'Audio',
    price: 899,
    originalPrice: 1099,
    image: 'https://picsum.photos/seed/airpods/600/600',
    description: 'Rebuilt from the sound up. Up to 2x more Active Noise Cancellation.',
    condition: 'Excellent',
    stock: 20,
    specs: {
      chip: 'H2 Apple Silicon',
      charging: 'MagSafe (USB-C)',
    },
  },
];

export const MOCK_SELL_REQUESTS: SellRequest[] = [
  {
    id: 'sr-1',
    userId: 'u-1',
    userName: 'Ahmad Fauzi',
    deviceName: 'iPhone 13 Pro',
    category: 'iPhone',
    condition: 'Excellent',
    estimatedPrice: 2200,
    status: 'Pending',
    createdAt: '2026-03-18T10:00:00Z',
    image: 'https://picsum.photos/seed/iphone13/200/200',
  },
  {
    id: 'sr-2',
    userId: 'u-2',
    userName: 'Siti Aminah',
    deviceName: 'iPad Air 4',
    category: 'iPad',
    condition: 'Good',
    estimatedPrice: 1500,
    status: 'Pending',
    createdAt: '2026-03-19T14:30:00Z',
    image: 'https://picsum.photos/seed/ipadair/200/200',
  },
  {
    id: 'sr-3',
    userId: 'u-3',
    userName: 'John Doe',
    deviceName: 'MacBook Pro 14 (M1)',
    category: 'MacBook',
    condition: 'Excellent',
    estimatedPrice: 4500,
    status: 'Approved',
    createdAt: '2026-03-15T09:00:00Z',
    image: 'https://picsum.photos/seed/mbp14/200/200',
  },
];

export const MOCK_SALES_DATA: SaleData[] = [
  { date: '2026-03-14', sales: 12, revenue: 15000 },
  { date: '2026-03-15', sales: 18, revenue: 22000 },
  { date: '2026-03-16', sales: 15, revenue: 19000 },
  { date: '2026-03-17', sales: 25, revenue: 35000 },
  { date: '2026-03-18', sales: 20, revenue: 28000 },
  { date: '2026-03-19', sales: 30, revenue: 42000 },
  { date: '2026-03-20', sales: 22, revenue: 31000 },
];
