import { Product, SellRequest, SaleData } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'iphone-15-pro-max',
    name: 'iPhone 15 Pro Max',
    category: 'iPhone',
    price: 4899,
    originalPrice: 5499,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=800',
    description: 'The ultimate iPhone with Titanium design, A17 Pro chip, and advanced camera system.',
    condition: 'Excellent',
    stock: 10,
    specs: {
      processor: 'A17 Pro',
      ram: '8GB',
      rom: '256GB',
      battery: '4422 mAh',
      color: 'Natural Titanium',
      screen: '6.7-inch Super Retina XDR',
    },
  },
  {
    id: 'iphone-15',
    name: 'iPhone 15',
    category: 'iPhone',
    price: 3499,
    originalPrice: 3899,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&q=80&w=800',
    description: 'Dynamic Island comes to iPhone 15. A16 Bionic chip and 48MP Main camera.',
    condition: 'Excellent',
    stock: 15,
    specs: {
      processor: 'A16 Bionic',
      ram: '6GB',
      rom: '128GB',
      battery: '3349 mAh',
      color: 'Blue',
      screen: '6.1-inch Super Retina XDR',
    },
  },
  {
    id: 'iphone-14-pro',
    name: 'iPhone 14 Pro',
    category: 'iPhone',
    price: 3299,
    originalPrice: 3999,
    image: 'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?auto=format&fit=crop&q=80&w=800',
    description: 'Pro. Beyond. Featuring Dynamic Island and Always-On display.',
    condition: 'Excellent',
    stock: 5,
    specs: {
      processor: 'A16 Bionic',
      ram: '6GB',
      rom: '128GB',
      battery: '3200 mAh',
      color: 'Deep Purple',
      screen: '6.1-inch Super Retina XDR',
    },
  },
  {
    id: 'ipad-pro-m2',
    name: 'iPad Pro 11-inch (M2)',
    category: 'iPad',
    price: 3499,
    originalPrice: 3899,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800',
    description: 'Astonishing performance. Incredibly advanced displays. Superfast wireless connectivity.',
    condition: 'Excellent',
    stock: 8,
    specs: {
      processor: 'Apple M2',
      ram: '8GB',
      rom: '256GB',
      battery: '7538 mAh',
      color: 'Space Gray',
      connectivity: 'Wi-Fi',
    },
  },
  {
    id: 'ipad-air-5',
    name: 'iPad Air (5th Gen)',
    category: 'iPad',
    price: 2499,
    originalPrice: 2899,
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?auto=format&fit=crop&q=80&w=800',
    description: 'Light. Bright. Full of might. Supercharged by the Apple M1 chip.',
    condition: 'Excellent',
    stock: 12,
    specs: {
      processor: 'Apple M1',
      ram: '8GB',
      rom: '64GB',
      battery: '28.6Wh',
      color: 'Blue',
    },
  },
  {
    id: 'macbook-pro-14-m3',
    name: 'MacBook Pro 14-inch (M3)',
    category: 'MacBook',
    price: 6899,
    originalPrice: 7499,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800',
    description: 'Mind-blowing. Head-turning. The most advanced chips ever built for a personal computer.',
    condition: 'Excellent',
    stock: 4,
    specs: {
      processor: 'Apple M3',
      ram: '16GB',
      rom: '512GB SSD',
      battery: '70Wh',
    },
  },
  {
    id: 'macbook-air-m2',
    name: 'MacBook Air 13-inch (M2)',
    category: 'MacBook',
    price: 4299,
    originalPrice: 4799,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=800',
    description: 'Strikingly thin design. Supercharged by M2. Up to 18 hours of battery life.',
    condition: 'Excellent',
    stock: 3,
    specs: {
      processor: 'Apple M2',
      ram: '8GB',
      rom: '256GB SSD',
      battery: '52.6Wh',
    },
  },
  {
    id: 'apple-watch-ultra-2',
    name: 'Apple Watch Ultra 2',
    category: 'Watch',
    price: 3299,
    originalPrice: 3799,
    image: 'https://images.unsplash.com/photo-1434493907317-a46b53b81882?auto=format&fit=crop&q=80&w=800',
    description: 'The most rugged and capable Apple Watch. Designed for the extremes.',
    condition: 'Excellent',
    stock: 6,
    specs: {
      processor: 'S9 SiP',
      ram: '1GB',
      rom: '64GB',
      battery: '564 mAh',
      size: '49mm',
      material: 'Titanium',
    },
  },
  {
    id: 'apple-watch-s9',
    name: 'Apple Watch Series 9',
    category: 'Watch',
    price: 1599,
    originalPrice: 1899,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=800',
    description: 'Smarter. Brighter. Mightier. The most powerful chip in Apple Watch ever.',
    condition: 'Excellent',
    stock: 12,
    specs: {
      processor: 'S9 SiP',
      ram: '1GB',
      rom: '64GB',
      battery: '308 mAh',
      size: '45mm',
      material: 'Aluminum',
    },
  },
  {
    id: 'airpods-max',
    name: 'AirPods Max',
    category: 'Audio',
    price: 1899,
    originalPrice: 2299,
    image: 'https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?auto=format&fit=crop&q=80&w=800',
    description: 'The ultimate listening experience. High-fidelity audio and industry-leading Noise Cancellation.',
    condition: 'Excellent',
    stock: 8,
    specs: {
      processor: 'H1 Chip (x2)',
      battery: '20 hours',
      rom: 'N/A',
      ram: 'N/A',
    },
  },
  {
    id: 'airpods-pro-2',
    name: 'AirPods Pro (2nd Gen)',
    category: 'Audio',
    price: 899,
    originalPrice: 1099,
    image: 'https://images.unsplash.com/photo-1588423770574-0107a6633833?auto=format&fit=crop&q=80&w=800',
    description: 'Rebuilt from the sound up. Up to 2x more Active Noise Cancellation.',
    condition: 'Excellent',
    stock: 20,
    specs: {
      processor: 'H2 Chip',
      battery: '6 hours',
      charging: 'MagSafe (USB-C)',
    },
  },
  {
    id: 'samsung-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    category: 'Android',
    price: 5299,
    originalPrice: 6299,
    image: 'https://images.unsplash.com/photo-1707227156649-035158397955?auto=format&fit=crop&q=80&w=800',
    description: 'Galaxy AI is here. Welcome to the era of mobile AI. With S24 Ultra, you can unleash whole new levels of creativity.',
    condition: 'Excellent',
    stock: 8,
    specs: {
      processor: 'Snapdragon 8 Gen 3',
      ram: '12GB',
      rom: '256GB',
      battery: '5000 mAh',
      color: 'Titanium Gray',
      screen: '6.8-inch QHD+ Dynamic AMOLED 2X',
    },
  },
  {
    id: 'google-pixel-8-pro',
    name: 'Google Pixel 8 Pro',
    category: 'Android',
    price: 3899,
    originalPrice: 4499,
    image: 'https://images.unsplash.com/photo-1696429117075-37307842771c?auto=format&fit=crop&q=80&w=800',
    description: 'The all-pro phone engineered by Google. Its sleek, sophisticated design features a polished aluminum frame.',
    condition: 'Excellent',
    stock: 5,
    specs: {
      processor: 'Google Tensor G3',
      ram: '12GB',
      rom: '128GB',
      battery: '5050 mAh',
      color: 'Bay',
      screen: '6.7-inch Super Actua display',
    },
  },
  {
    id: 'xiaomi-14-ultra',
    name: 'Xiaomi 14 Ultra',
    category: 'Android',
    price: 4599,
    originalPrice: 5199,
    image: 'https://images.unsplash.com/photo-1614624532983-4ce03382d63d?auto=format&fit=crop&q=80&w=800',
    description: 'Legendary Leica Optics. 1-inch main camera with variable aperture. Snapdragon 8 Gen 3.',
    condition: 'Excellent',
    stock: 3,
    specs: {
      processor: 'Snapdragon 8 Gen 3',
      ram: '16GB',
      rom: '512GB',
      battery: '5000 mAh',
      color: 'Black',
      screen: '6.73-inch AMOLED',
    },
  },
];

export const MOCK_SELL_REQUESTS: SellRequest[] = [
  {
    id: 'sr-1',
    userId: 'u-1',
    userName: 'Ahmad Fauzi',
    deviceName: 'iPhone 13 Pro',
    category: 'iPhone',
    condition: 'Excellent',
    estimatedPrice: 2200,
    status: 'Pending',
    createdAt: '2026-03-18T10:00:00Z',
    image: 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?auto=format&fit=crop&q=80&w=400',
    specs: {
      processor: 'A15 Bionic',
      ram: '6GB',
      rom: '128GB',
      battery: '3095 mAh'
    }
  },
  {
    id: 'sr-2',
    userId: 'u-2',
    userName: 'Siti Aminah',
    deviceName: 'iPad Air 4',
    category: 'iPad',
    condition: 'Good',
    estimatedPrice: 1500,
    status: 'Pending',
    createdAt: '2026-03-19T14:30:00Z',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=400',
    specs: {
      processor: 'A14 Bionic',
      ram: '4GB',
      rom: '64GB',
      battery: '7606 mAh'
    }
  },
  {
    id: 'sr-3',
    userId: 'u-3',
    userName: 'John Doe',
    deviceName: 'MacBook Pro 14 (M1)',
    category: 'MacBook',
    condition: 'Excellent',
    estimatedPrice: 4500,
    status: 'Approved',
    createdAt: '2026-03-15T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=400',
    specs: {
      processor: 'Apple M1 Pro',
      ram: '16GB',
      rom: '512GB SSD',
      battery: '70Wh'
    }
  },
];

export const MOCK_SALES_DATA: SaleData[] = [
  { date: '2026-03-14', sales: 12, revenue: 15000 },
  { date: '2026-03-15', sales: 18, revenue: 22000 },
  { date: '2026-03-16', sales: 15, revenue: 19000 },
  { date: '2026-03-17', sales: 25, revenue: 35000 },
  { date: '2026-03-18', sales: 20, revenue: 28000 },
  { date: '2026-03-19', sales: 30, revenue: 42000 },
  { date: '2026-03-20', sales: 22, revenue: 31000 },
];
